name: legendary_pokedex
description: A pokedex with the ability to filter legendary pokemons
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  csv: ^5.0.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/Pokemon.csv
